apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-playground-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: k8s-playground-updater-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: k8s-playground-sa-updater-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-playground-updater-role
subjects:
- kind: ServiceAccount
  name: k8s-playground-sa
  namespace: default
